DROP TABLE IF EXISTS `query_status`;

CREATE TABLE `query_status` (
    QUERY VARCHAR(63) NOT NULL,
    SITE VARCHAR(20) NOT NULL,
    DATE_STARTED DATETIME NOT NULL,
    GENOMIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'NotStarted',
    PHENOTYPIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'NotStarted',
    PRIMARY KEY (`QUERY`)
);

INSERT INTO `query_status` (QUERY, GENOMIC_STATUS, PHENOTYPIC_STATUS, SITE, DATE_STARTED)
    VALUES ('33613336-3934-3761-2d38-3233312d3131', 'Complete', 'Error', 'bch', now());