---
version: '3'
services:
  info-service:
    image: info-service:latest
    container_name: info-service
    build: infoservice/
    env_file:
      - infoservice/.env
    networks:
      - picsure
