---
version: '3'
services:
  info-service:
    image: info-service:latest
    container_name: info-service
    build: info-service/
    env_file:
      - info-service/.env
    networks:
      - picsure
