---
version: '3'
services:
  uploader:
    image: lukesikinabch/gic-uploader:1.2.3
    container_name: uploader
    ports:
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - uploader-db
    restart: always
    volumes:
      - $DOCKER_CONFIG_DIR/aws_uploads/:/gic_query_results/
    networks:
      - picsure
    profiles:
      - "production"
  uploader-db:
    image: mysql:8.0
    container_name: uploader-db
    # This is super confusing. There are actually two .env files: one for the docker-compose environment itself
    # and one for each container. This specifies the LATTER of those two envs
    # The variables on the right side of the environment section are from the FORMER of these two envs
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DATA_UPLOAD_DB_PASS
      MYSQL_PASSWORD: $DATA_UPLOAD_DB_PASS
      MYSQL_DATABASE: $DATA_UPLOAD_DB_DATABASE
      MYSQL_USER: $DATA_UPLOAD_DB_USER
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-u", "root", "-p$DATA_UPLOAD_DB_PASS" ]
      timeout: 20s
      retries: 10
    networks:
      - picsure
    restart: always
    volumes:
      - /usr/local/pic-sure-services/uploader/data/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
      - uploader-db-data:/var/lib/mysql
  migrations:
    image: flyway/flyway:11-alpine
    container_name: flyway
    command: -url=jdbc:mysql://uploader-db:3306/${DATA_UPLOAD_DB_DATABASE}?allowPublicKeyRetrieval=true -schemas=${DATA_UPLOAD_DB_DATABASE} -user=${DATA_UPLOAD_DB_USER} -password=${DATA_UPLOAD_DB_PASS} -connectRetries=60 -validateMigrationNaming=true migrate
    env_file:
      - .env
    volumes:
      - ./flyway:/flyway/sql
    networks:
      - picsure
    profiles:
      - "migrate"
    depends_on:
      - "uploader-db"
volumes:
  uploader-db-data:

networks:
  picsure:
    external: true
