name: Update Test Branch

on:
  push:
    branches: [main]
    
permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.SECRET_KEY}}
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "Luke Sikina"
          git config user.email "lucas.sikina@gmail.com"

      - name: Update Test Branch
        run: |
          git checkout main
          git fetch origin
          git checkout release
          git pull
          git rebase origin/main
          git push origin release --force

