name: Java CI with Maven

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: "for dir in 'uploader' 'info-service'; do cd $dir; mvn verify; cd ..; done" 

